server:
  port: 8080
spring:
  application:
    name: product
---
spring:
  config:
    activate:
      on-profile: default
  jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl      
  cloud:
    function: 
      routing-expression: "headers['type']=='DeliveryStarted' ? 'wheneverDeliveryStarted_DescreaseStock' : headers['type']=='DeliveryCancelled' ? 'wheneverDeliveryCancelled_IncreaseStock' : 'discardFunction'"
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
          functionRouter-in-0:              
            group: product
            destination: mallbasic
            contentType: application/json            
          producer-out-0:
            destination: mallbasic
            contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: docker
  jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl      
  cloud:
    function: 
      routing-expression: "headers['type']=='DeliveryStarted' ? 'wheneverDeliveryStarted_DescreaseStock' : headers['type']=='DeliveryCancelled' ? 'wheneverDeliveryCancelled_IncreaseStock' : 'discardFunction'"
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
      bindings:
          functionRouter-in-0:              
            group: product
            destination: mallbasic
            contentType: application/json            
          producer-out-0:
            destination: mallbasic
            contentType: application/json
