server:
  port: 8080

spring:
  application:
    name: order
---

spring:
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function: 
      definition: whatever;producer
    stream:
      kafka:
        binder:
          brokers: localhost:9092                          
      bindings:
        whatever-in-0:
          group: order
          destination: mallbasic
          contentType: application/json
        producer-out-0:
          destination: mallbasic
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function: 
      definition: whatever;producer
    stream:
      kafka:
        binder:
          brokers: localhost:9092                          
      bindings:
        whatever-in-0:
          group: order
          destination: mallbasic
          contentType: application/json
        producer-out-0:
          destination: mallbasic
          contentType: application/json


