server:
  port: 8080

spring:
  application:
    name: delivery
---

spring:
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function:      
      definition: wheneverOrderPlaced_StartDelivery;wheneverOrderCancelled_CancelDelivery;producer      
    stream:
      function:      
        bindings:
          wheneverOrderPlaced_StartDelivery-in-0: consumer-in-0
          wheneverOrderCancelled_CancelDelivery-in-0: consumer-in-0            
      kafka:
        bindings:
          configuration:
            default:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        binder:
          brokers: localhost:9092                          
      bindings:
        consumer-in-0:
          group: delivery
          destination: mallbasic
          consumer:
            condition: "headers['type']=='OrderPlaced' || headers['type']=='OrderCancelled'"
          contentType: application/json
        producer-out-0:
          destination: mallbasic
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8083

---

spring:
  config:
    activate:
      on-profile: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    function: 
      definition: consumer; producer
    stream:
      kafka:
        bindings:
          configuration:
            default:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        binder:
          brokers: my-kafka:9092                          
      bindings:
        consumer-in-0:
          group: delivery
          destination: mallbasic
          contentType: application/json
        producer-out-0:
          destination: mallbasic
          contentType: application/json


